### ISSUE TITLE
The module published to npm hasn't been built yet.

### ISSUE THREAD

**Issue by W1ndst0rm** [matiere-noire/redux-websocket#1]
The package.json main object specifies that the entry point is dist/index.js. This doesn't exist in module as it is currently published. 

I'm using this with create-react-app. Webpack cannot find the module and import it when the entry point is missing.

**Comment by croustibat** [comment]
Hi @W1ndst0rm,

I fixed the package.json file with correct path for the main section.
Thank for poiting us this issue.
