### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by ashfordneil** [matiere-noire/redux-websocket#2]
After following the setup instructions on the readme ( `$ yarn add matiere-noire/redux-websocket-autoreconnect` and `import websocket from matiere-noire/redux-websocket-autoreconnect`) I get the following error:

Unable to resolve module `matiere-noire/redux-websocket-autoreconnect` from `/path/to/file.js`: Module does not exist in module map or in these directories: `/path/to/node_modules/matiere-noire/`

**Comment by croustibat** [comment]
Hi @ashfordneil,

could you send more detail on your stack ?
