### ISSUE TITLE
Remove flow types from src or provide clean dist to use in NPM

### ISSUE THREAD

**Issue by andrevinsky** [matiere-noire/redux-websocket#3]
Compilation (by react-scripts) failing with the following log:
```

./node_modules/redux-websocket-autoreconnect/src/index.js
Module parse failed: Unexpected token (21:15)
You may need an appropriate loader to handle this file type.
| const createMiddleware = () => {
|   // Hold a reference to the WebSocket instance in use.
|   let websocket: ?WebSocket;
|   let websocketConfig: ?Config
```

Clearly, the code references `src` folder, and the files with the flow types in them. My flow settings are obscured by react-scripts. Cannot easily change them.

Probably you need to provide proper `main` properties in `package.json`. Feel free to contact me directly about it.

**Comment by dmitrysdm** [comment]
Problem still exist :(

At same time now module must be imported as:
import websocket from 'redux-websocket-autoreconnect'

**Comment by croustibat** [comment]
Hi guys,

We're not working actively on this project, we'll archive it. Feel free to fork ! 

Best,
