### ISSUE TITLE
Add support for configuring WebSocket binaryType

### ISSUE THREAD

**Issue by villhei** [matiere-noire/redux-websocket#4]
Hey,

I'm considering using this library, as it seems to fit my purposes quite nicely.

My use case requires setting the socket.binarytype to 'arraybuffer'. I'm willing to make a pull request (work in progress already) for this feature, along with tests. I'm opening an issue for tracking this feature.

My plan is to add a config option for binaryType, which defaults to the platform default (nodebuffer for WS implementation in the tests). I'll fix some flowtype issues,  will build a distributable copy of the library to `dist/` and perform some minor updates/fixes while at it.

Could you confirm, with a reply to this issue, that this package is still in maintenance?

**Comment by croustibat** [comment]
Hi zzcats, 

Thank you for opening this issue. Actually, we're not actively working on this project. One of the reason is that we switched from Redux to Mobx.

But feel free to start working on this project on your side.

We will archived this project on our side.

Have a good day.
